version: 2
# see options in https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    labels: ["kind: infrastructure"]
    groups:
      pip-dependencies:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels: ["kind: infrastructure"]
    groups:
      gh-actions-dependencies:
        patterns:
          - "*"
