# Build, test, and publish to releases, packages, PyPi, etc.
# Runs when creating a GitHub release
name: publish
on:
  release:
    types: [published]
  repository_dispatch:
    types: [release-made]
jobs:
  build:
    strategy:
      max-parallel: 1
      matrix:
        os: [ubuntu-20.04]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    uses: ./.github/workflows/test.yml
    with:
      python-version: ${{ matrix.python-version }}
      os: ${{ matrix.os }}
  deploy:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install build meta-dependencies
        run: |
          pip install poetry tox-gh>=1.2
      - name: Build sdists and wheels with Poetry
        run: |
          poetry build
          poetry install
      - name: Publish to PyPi
        run: |
          poetry publish -vv --username __token__ --password ${{ secrets.PYPI_TOKEN }}
