# Build, test, and publish to releases, packages, PyPi, etc.
# Runs when creating a GitHub release
name: publish
on:
  release:
    types: [published]
  repository_dispatch:
    types: [release-made]
jobs:
  build_wheels:
    name: Build wheel and upload
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: hynek/build-and-inspect-python-package@v1
      - uses: actions/download-artifact@v3
        with:
          name: Packages
          path: dist
      - uses: pypa/gh-action-pypi-publish@release/v1
