# Runs tests via tox
# Runs on pull requests to main
name: pulltest
on:
  pull_request:
    branches: [main, master]
    paths-ignore: ["**/*.md", "**/*.rst"]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    uses: ./.github/workflows/test.yml
    with:
      python-version: ${{ matrix.python-version }}
      os: ${{ matrix.os }}
