# Build, test, and run static analyses, and send reports to external services
# Runs only on pushing to main
name: maintest
on:
  push:
    branches: [main, master]
jobs:
  coverage:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: "Set up Python 3.11"
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install build meta-dependencies
        run: |
          pip install poetry tox-gh>=1.2
      - name: Test with tox
        run: |
          tox -e coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
