# Runs tests via tox
name: test
on:
  workflow_call:
    inputs:
      python-version:
        description: "The python version to use"
        default: "3.9"
        required: false
        type: string
      os:
        description: "The OS to use"
        default: "ubuntu-20.04"
        required: false
        type: string
jobs:
  build:
    runs-on: "${{ inputs.os }}"
    steps:
      - name: Free up space
        uses: jlumbroso/free-disk-space@v1
        with:
          tool-cache: false
      - name: Checkout
        uses: actions/checkout@v4
      - name: "Set up Python ${{ inputs.python-version }} "
        uses: actions/setup-python@v4
        with:
          python-version: "${{ inputs.python-version }} "
      - name: Install build meta-dependencies
        run: |
          pip install poetry tox-gh>=1.2
      - name: Setup test suite
        run: |
          tox -vv --notest
      - name: Test with tox
        run: |
          tox --skip-pkg-install
